const $=selector=>document.querySelector(selector),CONFIG={url:"https://tlqgxoadvhexotssbtmf.supabase.co",key:"sb_publishable_Hswr0fwUuFv1bTWpaFYArQ_Ozei32TQ"},SESSION_KEY="my-money-cloud-session",DB_NAME="my-money-db",STORES=["transactions","recurring"];let authMode="signup",restoreInProgress=false;
const session=()=>JSON.parse(localStorage.getItem(SESSION_KEY)||"null"),setStatus=(message,target="#authStatus")=>$(target).textContent=message;
const request=operation=>new Promise((resolve,reject)=>{operation.onsuccess=()=>resolve(operation.result);operation.onerror=()=>reject(operation.error)});
async function openDatabase(){return new Promise((resolve,reject)=>{const operation=indexedDB.open(DB_NAME,2);operation.onupgradeneeded=()=>{for(const store of STORES)if(!operation.result.objectStoreNames.contains(store))operation.result.createObjectStore(store,{keyPath:"id"})};operation.onsuccess=()=>resolve(operation.result);operation.onerror=()=>reject(operation.error)})}
async function localData(){const database=await openDatabase(),transaction=database.transaction(STORES),transactions=await request(transaction.objectStore("transactions").getAll()),monthlyPlans=await request(transaction.objectStore("recurring").getAll());database.close();return{transactions,monthlyPlans}}
async function validSession(){let current=session();if(!current)throw Error("Please sign in first.");if(current.expires_at*1000>Date.now()+60000)return current;const response=await fetch(CONFIG.url+"/auth/v1/token?grant_type=refresh_token",{method:"POST",headers:{apikey:CONFIG.key,"Content-Type":"application/json"},body:JSON.stringify({refresh_token:current.refresh_token})});if(!response.ok)throw Error("Your sign-in expired. Please sign in again.");current=await response.json();localStorage.setItem(SESSION_KEY,JSON.stringify(current));return current}
async function api(path,options={}){const current=options.session||await validSession(),response=await fetch(CONFIG.url+path,{...options,headers:{apikey:CONFIG.key,Authorization:"Bearer "+current.access_token,"Content-Type":"application/json",...(options.headers||{})}});const text=await response.text();if(!response.ok)throw Error((text&&JSON.parse(text).message)||"Cloud request failed.");return text?JSON.parse(text):null}
function draw(){const current=session(),signed=!!current;$("#accountChoice").hidden=signed;$("#authForm").hidden=true;$("#signedIn").hidden=!signed;if(signed)$("#accountEmail").textContent=current.user.email}
function showAuth(mode){authMode=mode;const signUp=mode==="signup";$("#accountChoice").hidden=true;$("#authForm").hidden=false;$("#authTitle").textContent=signUp?"Create your backup account":"Sign in to cloud backup";$("#authHelp").textContent=signUp?"Choose an email and password that you can remember.":"Enter the same email and password you used for cloud backup.";$("#authSubmit").textContent=signUp?"Create account":"Sign in";$("#switchAuth").textContent=signUp?"Already have an account? Sign in":"New here? Create a backup account";$("#password").autocomplete=signUp?"new-password":"current-password";setStatus("");$("#email").focus()}
async function authenticate(){const signUp=authMode==="signup",email=$("#email").value.trim(),password=$("#password").value;if(!email||password.length<8){setStatus("Enter a valid email and a password with at least 8 characters.");return}try{const path=signUp?"/auth/v1/signup":"/auth/v1/token?grant_type=password",response=await fetch(CONFIG.url+path,{method:"POST",headers:{apikey:CONFIG.key,"Content-Type":"application/json"},body:JSON.stringify({email,password})}),data=await response.json();if(!response.ok)throw Error(data.message||data.msg||"Could not sign in.");if(!data.access_token){setStatus(data.user?.identities?.length===0?"This email already has an account. Select Sign in instead.":"Account created. Please select Sign in.");return}localStorage.setItem(SESSION_KEY,JSON.stringify(data));$("#password").value="";draw();await backup()}catch(error){setStatus(error.message.includes("rate limit")?"Too many attempts were made recently. Wait a few minutes, then use Sign in.":error.message)}}
async function backup(){try{const current=await validSession(),data=await localData();await api("/rest/v1/my_money_backups?on_conflict=user_id",{session:current,method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({user_id:current.user.id,data:{version:1,exportedAt:new Date().toISOString(),...data},updated_at:new Date().toISOString()})});setStatus("Cloud backup saved at "+new Date().toLocaleTimeString()+".","#backupStatus")}catch(error){setStatus(error.message,"#backupStatus")}}
async function restore(){try{const current=await validSession(),rows=await api("/rest/v1/my_money_backups?user_id=eq."+current.user.id+"&select=data,updated_at",{session:current});if(!rows.length){setStatus("No cloud backup found yet.","#backupStatus");return}const data=rows[0].data;if(!Array.isArray(data?.transactions)||!Array.isArray(data?.monthlyPlans))throw Error("This cloud backup is not valid.");if(!confirm("Restore "+data.transactions.length+" transactions and "+data.monthlyPlans.length+" monthly plans? This replaces data currently on this phone."))return;restoreInProgress=true;const database=await openDatabase(),transaction=database.transaction(STORES,"readwrite");for(const store of STORES){const objectStore=transaction.objectStore(store);await request(objectStore.clear());for(const item of store==="transactions"?data.transactions:data.monthlyPlans)await request(objectStore.put(item))}database.close();setStatus("Cloud backup restored. Last saved "+new Date(rows[0].updated_at).toLocaleString()+".","#backupStatus")}catch(error){setStatus(error.message,"#backupStatus")}finally{restoreInProgress=false}}
$("#createAccount").onclick=()=>showAuth("signup");$("#signIn").onclick=()=>showAuth("signin");$("#switchAuth").onclick=()=>showAuth(authMode==="signup"?"signin":"signup");$("#authForm").onsubmit=event=>{event.preventDefault();authenticate()};$("#backupNow").onclick=backup;$("#restoreNow").onclick=restore;$("#signOut").onclick=()=>{localStorage.removeItem(SESSION_KEY);draw()};draw();if(location.hash==="#signin")showAuth("signin");if(location.hash==="#signup")showAuth("signup");
