const cloud$ = selector => document.querySelector(selector);
const CLOUD_CONFIG = "my-money-cloud-config", CLOUD_SESSION = "my-money-cloud-session";
const CLOUD_DEFAULT = {url:"https://tlqgxoadvhexotssbtmf.supabase.co",key:"sb_publishable_Hswr0fwUuFv1bTWpaFYArQ_Ozei32TQ"};
let cloudTimer,cloudRestoreInProgress=false;
const cloudConfig = () => ({...CLOUD_DEFAULT,...JSON.parse(localStorage.getItem(CLOUD_CONFIG) || "{}")});
const cloudSession = () => JSON.parse(localStorage.getItem(CLOUD_SESSION) || "null");
const cloudSetStatus = message => { cloud$("#cloudStatus").textContent = message;const dialogMessage=cloud$("#cloudAuthMessage");if(dialogMessage)dialogMessage.textContent=message; };
function cloudHeaders(token) { const config=cloudConfig(); return {apikey:config.key,Authorization:"Bearer "+(token || cloudSession()?.access_token),"Content-Type":"application/json"}; }
function cloudReady() { const config=cloudConfig(); return config.url && config.key; }
async function cloudFetch(path, options={}) { const config=cloudConfig(),response=await fetch(config.url.replace(/\/$/,"")+path,{...options,headers:{...cloudHeaders(options.token),...(options.headers||{})}});if(!response.ok)throw Error((await response.json().catch(()=>({}))).message||"Cloud request failed ("+response.status+").");const body=await response.text();return body?JSON.parse(body):null; }
function cloudDraw() { const session=cloudSession();cloud$("#cloudSetup").hidden=!!session;cloud$("#cloudSignedIn").hidden=!session;cloud$("#cloudAccount").textContent=session?"Signed in as "+session.user.email:"";if(!session)cloudSetStatus("Create an account once, then use the same email and password whenever you need to restore your data."); }
async function cloudRefreshSession() { const session=cloudSession();if(!session?.refresh_token||session.expires_at*1000>Date.now()+60000)return session;const config=cloudConfig(),response=await fetch(config.url.replace(/\/$/,"")+"/auth/v1/token?grant_type=refresh_token",{method:"POST",headers:{apikey:config.key,"Content-Type":"application/json"},body:JSON.stringify({refresh_token:session.refresh_token})});if(!response.ok)throw Error("Your cloud session expired. Please sign in again.");const next=await response.json();localStorage.setItem(CLOUD_SESSION,JSON.stringify(next));return next; }
async function cloudSnapshot() { return {version:1,exportedAt:new Date().toISOString(),transactions:await allTransactions(),monthlyPlans:await recurItems()}; }
async function cloudBackup(silent=false) { if(!cloudReady()||!cloudSession())return;try {const session=await cloudRefreshSession(),data=await cloudSnapshot();await cloudFetch("/rest/v1/my_money_backups?on_conflict=user_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({user_id:session.user.id,data,updated_at:new Date().toISOString()})});cloudSetStatus("Cloud backup saved at "+new Date().toLocaleTimeString()+".");}catch(error){if(!silent)cloudSetStatus(error.message);}}
async function cloudRestore(silentParam) { const silent = silentParam === true; try {const session=await cloudRefreshSession(),rows=await cloudFetch("/rest/v1/my_money_backups?user_id=eq."+session.user.id+"&select=data,updated_at");if(!rows.length){if(!silent)cloudSetStatus("No cloud backup found yet.");return}const backup=rows[0].data;if(!backup||!Array.isArray(backup.transactions)||!Array.isArray(backup.monthlyPlans))throw Error("The cloud backup is not valid.");if(!silent&&!confirm("Restore "+backup.transactions.length+" transactions and "+backup.monthlyPlans.length+" monthly plans from cloud? This replaces data currently on this phone."))return;cloudRestoreInProgress=true;clearTimeout(cloudTimer);await clearTransactions();for(const item of backup.transactions)await saveTransaction(item);const planStore=db.transaction(recurStore,"readwrite").objectStore(recurStore);await recurRequest(planStore.clear());for(const item of backup.monthlyPlans)await saveRecur(item);await refresh();await renderRecurring();cloudSetStatus("Cloud backup restored. Last saved "+new Date(rows[0].updated_at).toLocaleString()+".");}catch(error){cloudSetStatus(error.message);}finally{cloudRestoreInProgress=false}}
let cloudAuthMode="signup";
function openCloudAuth(mode){cloudAuthMode=mode;const signUp=mode==="signup",dialog=cloud$("#cloudAuthDialog");cloud$("#cloudAuthTitle").textContent=signUp?"Create your backup account":"Sign in to cloud backup";cloud$("#cloudAuthHelp").textContent=signUp?"Use an email you can remember. This account lets you safely restore your data on a new phone.":"Enter the email and password you used when you created your backup account.";cloud$("#cloudAuthSubmit").textContent=signUp?"Create account":"Sign in";cloud$("#cloudAuthSwitch").textContent=signUp?"Already have an account? Sign in":"New here? Create a backup account";cloud$("#cloudAuthPassword").autocomplete=signUp?"new-password":"current-password";cloud$("#cloudAuthMessage").textContent="";if(!dialog.open)dialog.showModal();cloud$("#cloudAuthEmail").focus()}
async function cloudAuth() { const signUp=cloudAuthMode==="signup";if(!cloudReady()){cloudSetStatus("Cloud backup is not ready. Please try again shortly.");return}const email=cloud$("#cloudAuthEmail").value.trim(),password=cloud$("#cloudAuthPassword").value;if(!email||password.length<8){cloudSetStatus("Enter a valid email and a password with at least 8 characters.");return}try {const config=cloudConfig(),path=signUp?"/auth/v1/signup":"/auth/v1/token?grant_type=password",body={email,password},response=await fetch(config.url.replace(/\/$/,"")+path,{method:"POST",headers:{apikey:config.key,"Content-Type":"application/json"},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)throw Error(data.msg||data.message||"Could not sign in.");if(!data.access_token){cloudSetStatus(data.user?.identities?.length===0?"This email already has an account. Select Sign in instead.":"Account created. Please select Sign in with the same email and password.");return}localStorage.setItem(CLOUD_SESSION,JSON.stringify(data));cloud$("#cloudAuthPassword").value="";cloud$("#cloudAuthDialog").close();cloudDraw();if(signUp){await clearTransactions();const planStore=db.transaction(recurStore,"readwrite").objectStore(recurStore);await recurRequest(planStore.clear());await refresh();await renderRecurring();await cloudBackup();}else{await cloudRestore(true);}}catch(error){const message=error.message.includes("rate limit")?"Too many attempts were made recently. Wait a few minutes, then select Sign in if the account already exists.":error.message;cloudSetStatus(message);}}
function queueCloudSync() { if(cloudRestoreInProgress)return;clearTimeout(cloudTimer);cloudTimer=setTimeout(()=>cloudBackup(true),1200); }
function cloudSetup() { cloud$("#cloudOpenSignIn").onclick=()=>openCloudAuth("signin");cloud$("#cloudOpenSignUp").onclick=()=>openCloudAuth("signup");cloud$("#closeCloudAuth").onclick=()=>cloud$("#cloudAuthDialog").close();cloud$("#cloudAuthSwitch").onclick=()=>openCloudAuth(cloudAuthMode==="signup"?"signin":"signup");cloud$("#cloudAuthForm").onsubmit=event=>{event.preventDefault();cloudAuth()};cloud$("#cloudSync").onclick=()=>cloudBackup();cloud$("#cloudRestore").onclick=()=>cloudRestore();cloud$("#cloudSignOut").onclick=()=>{localStorage.removeItem(CLOUD_SESSION);cloudSetStatus("Signed out. Your cloud backup remains safe.");cloudDraw()};cloudDraw() }
const cloudStyle=document.createElement("style");cloudStyle.textContent=".cloud-section{margin-top:25px;padding:17px;border:1px solid #bcdac7;border-radius:16px;background:#f3fbf6}.cloud-section h2{font-size:1.05rem}.cloud-section p{color:#456050;font-size:.8rem;line-height:1.45;margin:5px 0 12px}.cloud-welcome{display:grid;grid-template-columns:auto 1fr;gap:12px;align-items:center;margin-top:14px;padding:14px;border-radius:13px;background:#fff}.cloud-welcome h3{margin:0;font-size:.95rem}.cloud-welcome p{margin:3px 0 0}.cloud-welcome-icon{display:grid;place-items:center;width:40px;height:40px;border-radius:50%;background:#dff2e5;color:#155e3a;font-size:1.25rem}.cloud-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:11px}.cloud-welcome .cloud-actions{grid-column:1/-1;margin-top:0}.cloud-auth-dialog{width:min(100% - 28px,420px);border:0;border-radius:20px;padding:0;box-shadow:0 18px 60px #16281d66}.cloud-auth-dialog::backdrop{background:#10251ab3}.cloud-auth-dialog form{display:grid;gap:13px;padding:23px}.cloud-auth-dialog .dialog-heading{align-items:flex-start}.cloud-auth-dialog .eyebrow{margin:0;color:#1d6b43;font-weight:800;letter-spacing:.08em;font-size:.68rem}.cloud-auth-dialog h2{margin:4px 0 0;font-size:1.3rem}.cloud-auth-dialog label{display:grid;gap:6px;font-weight:700;font-size:.85rem}.cloud-auth-dialog input{min-height:46px;padding:0 12px;border:1px solid #c9d4cc;border-radius:10px;font:inherit}.cloud-password-help{margin:-6px 0 0!important;font-size:.74rem!important}.cloud-auth-dialog .save-button{width:100%;margin-top:2px}.cloud-switch{justify-self:center}.danger-lite{color:#a1251e;border-color:#f1b8b2}@media(max-width:420px){.cloud-welcome .cloud-actions{display:grid}.cloud-welcome .cloud-actions button{width:100%}}";document.head.append(cloudStyle);setTimeout(cloudSetup,700);
