const cloud$ = selector => document.querySelector(selector);
const CLOUD_CONFIG = "my-money-cloud-config", CLOUD_SESSION = "my-money-cloud-session";
const CLOUD_DEFAULT = {url:"https://tlqgxoadvhexotssbtmf.supabase.co",key:"sb_publishable_Hswr0fwUuFv1bTWpaFYArQ_Ozei32TQ"};
let cloudTimer,cloudRestoreInProgress=false;
const cloudConfig = () => ({...CLOUD_DEFAULT,...JSON.parse(localStorage.getItem(CLOUD_CONFIG) || "{}")});
const cloudSession = () => JSON.parse(localStorage.getItem(CLOUD_SESSION) || "null");
const cloudSetStatus = message => { cloud$("#cloudStatus").textContent = message;const dialogMessage=cloud$("#cloudAuthMessage");if(dialogMessage)dialogMessage.textContent=message; };
function cloudHeaders(token) { const config=cloudConfig(); return {apikey:config.key,Authorization:"Bearer "+(token || cloudSession()?.access_token),"Content-Type":"application/json"}; }
function cloudReady() { const config=cloudConfig(); return config.url && config.key; }
async function cloudFetch(path, options={}) { const config=cloudConfig(),response=await fetch(config.url.replace(/\/$/,"")+path,{...options,headers:{...cloudHeaders(options.token),...(options.headers||{})}});if(!response.ok)throw Error((await response.json().catch(()=>({}))).message||"Cloud request failed ("+response.status+").");const body=await response.text();return body?JSON.parse(body):null; }
function cloudDraw() { const session=cloudSession(); if(session) { cloud$("#loginScreen").hidden = true; cloud$("#mainContent").hidden = false; } else { cloud$("#loginScreen").hidden = false; cloud$("#mainContent").hidden = true; } }
async function cloudRefreshSession() { const session=cloudSession();if(!session?.refresh_token||session.expires_at*1000>Date.now()+60000)return session;const config=cloudConfig(),response=await fetch(config.url.replace(/\/$/,"")+"/auth/v1/token?grant_type=refresh_token",{method:"POST",headers:{apikey:config.key,"Content-Type":"application/json"},body:JSON.stringify({refresh_token:session.refresh_token})});if(!response.ok)throw Error("Your cloud session expired. Please sign in again.");const next=await response.json();localStorage.setItem(CLOUD_SESSION,JSON.stringify(next));return next; }
async function cloudSnapshot() { return {version:1,exportedAt:new Date().toISOString(),transactions:await allTransactions(),monthlyPlans:await recurItems()}; }
async function cloudBackup(silent=false) { if(!cloudReady()||!cloudSession())return;try {const session=await cloudRefreshSession(),data=await cloudSnapshot();await cloudFetch("/rest/v1/my_money_backups?on_conflict=user_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({user_id:session.user.id,data,updated_at:new Date().toISOString()})});cloudSetStatus("Cloud backup saved at "+new Date().toLocaleTimeString()+".");}catch(error){if(!silent)cloudSetStatus(error.message);}}
async function cloudRestore(silentParam) { const silent = silentParam === true; try {const session=await cloudRefreshSession(),rows=await cloudFetch("/rest/v1/my_money_backups?user_id=eq."+session.user.id+"&select=data,updated_at");if(!rows.length){if(!silent)cloudSetStatus("No cloud backup found yet.");return}const backup=rows[0].data;if(!backup||!Array.isArray(backup.transactions)||!Array.isArray(backup.monthlyPlans))throw Error("The cloud backup is not valid.");if(!silent&&!confirm("Restore "+backup.transactions.length+" transactions and "+backup.monthlyPlans.length+" monthly plans from cloud? This replaces data currently on this phone."))return;cloudRestoreInProgress=true;clearTimeout(cloudTimer);await clearTransactions();for(const item of backup.transactions)await saveTransaction(item);const planStore=db.transaction(recurStore,"readwrite").objectStore(recurStore);await recurRequest(planStore.clear());for(const item of backup.monthlyPlans)await saveRecur(item);await refresh();await renderRecurring();cloudSetStatus("Cloud backup restored. Last saved "+new Date(rows[0].updated_at).toLocaleString()+".");}catch(error){cloudSetStatus(error.message);}finally{cloudRestoreInProgress=false}}
let cloudAuthMode="signin";
function openCloudAuth(mode){cloudAuthMode=mode;const signUp=mode==="signup";cloud$("#cloudAuthTitle").textContent=signUp?"Create your account":"Sign in to your account";cloud$("#cloudAuthHelp").textContent=signUp?"Use an email you can remember to create your secure account.":"Use your email and password to securely access your data.";cloud$("#cloudAuthSubmit").textContent=signUp?"Create account":"Sign in";cloud$("#cloudAuthSwitch").textContent=signUp?"Already have an account? Sign in":"New here? Create an account";cloud$("#cloudAuthPassword").autocomplete=signUp?"new-password":"current-password";cloud$("#cloudAuthMessage").textContent="";cloud$("#cloudAuthEmail").focus()}
async function cloudAuth() { const signUp=cloudAuthMode==="signup";if(!cloudReady()){cloudSetStatus("Cloud backup is not ready. Please try again shortly.");return}const email=cloud$("#cloudAuthEmail").value.trim(),password=cloud$("#cloudAuthPassword").value;if(!email||password.length<8){cloudSetStatus("Enter a valid email and a password with at least 8 characters.");return}try {const config=cloudConfig(),path=signUp?"/auth/v1/signup":"/auth/v1/token?grant_type=password",body={email,password},response=await fetch(config.url.replace(/\/$/,"")+path,{method:"POST",headers:{apikey:config.key,"Content-Type":"application/json"},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)throw Error(data.msg||data.message||"Could not sign in.");if(!data.access_token){cloudSetStatus(data.user?.identities?.length===0?"This email already has an account. Select Sign in instead.":"Account created. Please select Sign in with the same email and password.");return}localStorage.setItem(CLOUD_SESSION,JSON.stringify(data));cloud$("#cloudAuthPassword").value="";cloudDraw();if(signUp){await clearTransactions();if(typeof recurStore!=="undefined"&&typeof db!=="undefined"){const planStore=db.transaction(recurStore,"readwrite").objectStore(recurStore);await recurRequest(planStore.clear());}if(typeof refresh==="function")await refresh();if(typeof renderRecurring==="function")await renderRecurring();await cloudBackup();}else{await cloudRestore(true);}}catch(error){const message=error.message.includes("rate limit")?"Too many attempts were made recently. Wait a few minutes, then select Sign in if the account already exists.":error.message;cloudSetStatus(message);}}
function queueCloudSync() { if(cloudRestoreInProgress)return;clearTimeout(cloudTimer);cloudTimer=setTimeout(()=>cloudBackup(true),1200); }
function cloudSetup() { if(cloud$("#cloudAuthSwitch"))cloud$("#cloudAuthSwitch").onclick=()=>openCloudAuth(cloudAuthMode==="signup"?"signin":"signup");if(cloud$("#cloudAuthForm"))cloud$("#cloudAuthForm").onsubmit=event=>{event.preventDefault();cloudAuth()};if(cloud$("#cloudSignOut"))cloud$("#cloudSignOut").onclick=async()=>{localStorage.removeItem(CLOUD_SESSION);await clearTransactions();if(typeof recurStore!=="undefined"&&typeof db!=="undefined"){const planStore=db.transaction(recurStore,"readwrite").objectStore(recurStore);await recurRequest(planStore.clear());}if(typeof refresh==="function")await refresh();if(typeof renderRecurring==="function")await renderRecurring();cloudSetStatus("Signed out safely. Data removed from device.");cloudDraw()};cloudDraw();openCloudAuth("signin"); }
const cloudStyle=document.createElement("style");cloudStyle.textContent=".login-screen{position:fixed;z-index:10;inset:0;display:grid;place-items:center;padding:18px;background:linear-gradient(135deg,#103b29,#1b7043)} .login-screen form{width:min(100%,390px);padding:30px;border-radius:23px;background:#fff;display:grid;gap:14px;box-shadow:0 18px 60px #16281d66} .login-screen[hidden]{display:none} .login-screen .dialog-heading{align-items:flex-start;display:flex;justify-content:space-between} .login-screen .eyebrow{margin:0;color:#1d6b43;font-weight:800;letter-spacing:.08em;font-size:.68rem} .login-screen h2{margin:4px 0 0;font-size:1.3rem} .login-screen label{display:grid;gap:6px;font-weight:700;font-size:.85rem} .login-screen input{min-height:46px;padding:0 12px;border:1px solid #c9d4cc;border-radius:10px;font:inherit} .cloud-password-help{margin:-6px 0 0!important;font-size:.74rem!important} .login-screen .save-button{width:100%;margin-top:2px;border:0;border-radius:10px;background:#155e3a;color:#fff;padding:13px;font-weight:800} .cloud-switch{justify-self:center;background:transparent;border:0;color:#155e3a;font-weight:800;cursor:pointer;margin-top:8px}";document.head.append(cloudStyle);setTimeout(cloudSetup,700);
