const cloudAuthConfig={url:"https://tlqgxoadvhexotssbtmf.supabase.co",key:"sb_publishable_Hswr0fwUuFv1bTWpaFYArQ_Ozei32TQ"},cloudAuthSessionKey="my-money-cloud-session";let cloudAuthMode="signin";
const cloudAuth$=selector=>document.querySelector(selector),cloudAuthRequest=operation=>new Promise((resolve,reject)=>{operation.onsuccess=()=>resolve(operation.result);operation.onerror=()=>reject(operation.error)}),cloudAuthSession=()=>JSON.parse(localStorage.getItem(cloudAuthSessionKey)||"null");
function cloudAuthMessage(message){cloudAuth$("#cloudAuthMessage").textContent=message}
function showLogin(){cloudAuth$("#mainContent").hidden=true;cloudAuth$("#loginScreen").hidden=false}
function showDashboard(){cloudAuth$("#loginScreen").hidden=true;cloudAuth$("#mainContent").hidden=false}
function setupAuthMode(mode){cloudAuthMode=mode;const signUp=mode==="signup";cloudAuth$("#cloudAuthTitle").textContent=signUp?"Create your My Money account":"Sign in to My Money";cloudAuth$("#cloudAuthHelp").textContent=signUp?"Create one account to securely save and restore your money records.":"Use your email and password to safely open your money dashboard.";cloudAuth$("#cloudAuthSubmit").textContent=signUp?"Create account":"Sign in";cloudAuth$("#cloudAuthSwitch").textContent=signUp?"Already have an account? Sign in":"New here? Create an account";cloudAuth$("#cloudAuthPassword").autocomplete=signUp?"new-password":"current-password";cloudAuthMessage("")}
async function activeCloudSession(){let current=cloudAuthSession();if(!current)return null;if(current.expires_at*1000>Date.now()+60000)return current;try{const response=await fetch(cloudAuthConfig.url+"/auth/v1/token?grant_type=refresh_token",{method:"POST",headers:{apikey:cloudAuthConfig.key,"Content-Type":"application/json"},body:JSON.stringify({refresh_token:current.refresh_token})});if(!response.ok)throw Error();current=await response.json();localStorage.setItem(cloudAuthSessionKey,JSON.stringify(current));return current}catch{localStorage.removeItem(cloudAuthSessionKey);return null}}
async function restoreCloudData(current){const response=await fetch(cloudAuthConfig.url+"/rest/v1/my_money_backups?user_id=eq."+current.user.id+"&select=data,updated_at",{headers:{apikey:cloudAuthConfig.key,Authorization:"Bearer "+current.access_token}});if(!response.ok)throw Error("Could not load your cloud backup.");const rows=await response.json();if(!rows.length)return false;const backup=rows[0].data;if(!Array.isArray(backup?.transactions)||!Array.isArray(backup?.monthlyPlans))return false;window.myMoneyRestoring=true;try{if(!db)await openDB();await cloudAuthRequest(store("readwrite").clear());for(const item of backup.transactions)await cloudAuthRequest(store("readwrite").put(item));const planStore=db.transaction(recurStore,"readwrite").objectStore(recurStore);await cloudAuthRequest(planStore.clear());for(const item of backup.monthlyPlans)await cloudAuthRequest(planStore.put(item));await refresh();if(document.querySelector("#recurringList"))await renderRecurring();return true}finally{window.myMoneyRestoring=false}}
async function enterDashboard(current){cloudAuthMessage("Loading your saved records…");try{const restored=await restoreCloudData(current);showDashboard();if(restored)cloudAuthMessage("");else cloudAuthMessage("")}catch(error){showDashboard();alert(error.message+" Your local records are still available.")}}
async function submitCloudAuth(){const email=cloudAuth$("#cloudAuthEmail").value.trim(),password=cloudAuth$("#cloudAuthPassword").value,signUp=cloudAuthMode==="signup";if(!email||password.length<8){cloudAuthMessage("Enter a valid email and a password with at least 8 characters.");return}cloudAuthMessage(signUp?"Creating your account…":"Signing in…");try{const response=await fetch(cloudAuthConfig.url+(signUp?"/auth/v1/signup":"/auth/v1/token?grant_type=password"),{method:"POST",headers:{apikey:cloudAuthConfig.key,"Content-Type":"application/json"},body:JSON.stringify({email,password})}),data=await response.json();if(!response.ok)throw Error(data.message||data.msg||"Could not sign in.");if(!data.access_token){cloudAuthMessage(data.user?.identities?.length===0?"This email already has an account. Please sign in instead.":"Account created. Please sign in with the same email and password.");if(data.user?.identities?.length===0)setupAuthMode("signin");return}localStorage.setItem(cloudAuthSessionKey,JSON.stringify(data));cloudAuth$("#cloudAuthPassword").value="";await enterDashboard(data)}catch(error){cloudAuthMessage(error.message.includes("rate limit")?"Too many attempts were made recently. Wait a few minutes, then try Sign in.":error.message)}}
async function signOut(){if(!confirm("Log out and remove the downloaded data from this phone? Your cloud backup stays safe."))return;try{window.myMoneyRestoring=true;if(!db)await openDB();await cloudAuthRequest(store("readwrite").clear());const planStore=db.transaction(recurStore,"readwrite").objectStore(recurStore);await cloudAuthRequest(planStore.clear());state.transactions=[];if(typeof renderRecurring==="function")await renderRecurring();await refresh()}finally{window.myMoneyRestoring=false;localStorage.removeItem(cloudAuthSessionKey);cloudAuth$("#cloudAuthEmail").value="";cloudAuth$("#cloudAuthPassword").value="";setupAuthMode("signin");showLogin()}}
function startCloudAuth(){cloudAuth$("#cloudAuthForm").onsubmit=event=>{event.preventDefault();submitCloudAuth()};cloudAuth$("#cloudAuthSwitch").onclick=()=>setupAuthMode(cloudAuthMode==="signin"?"signup":"signin");cloudAuth$("#cloudSignOut").onclick=signOut;setupAuthMode("signin");const continueAfterLock=async()=>{const current=await activeCloudSession();if(current)await enterDashboard(current);else showLogin()};window.addEventListener("my-money-unlocked",continueAfterLock);if(cloudAuth$("#lockScreen").hidden)continueAfterLock()}
setTimeout(startCloudAuth,0);
