const cloud$ = selector => document.querySelector(selector);
const CLOUD_CONFIG = "my-money-cloud-config", CLOUD_SESSION = "my-money-cloud-session";
let cloudTimer;
const cloudConfig = () => JSON.parse(localStorage.getItem(CLOUD_CONFIG) || "{}");
const cloudSession = () => JSON.parse(localStorage.getItem(CLOUD_SESSION) || "null");
const cloudSetStatus = message => { cloud$("#cloudStatus").textContent = message; };
function cloudHeaders(token) { const config=cloudConfig(); return {apikey:config.key,Authorization:"Bearer "+(token || cloudSession()?.access_token),"Content-Type":"application/json"}; }
function cloudReady() { const config=cloudConfig(); return config.url && config.key; }
async function cloudFetch(path, options={}) { const config=cloudConfig(),response=await fetch(config.url.replace(/\/$/,"")+path,{...options,headers:{...cloudHeaders(options.token),...(options.headers||{})}});if(!response.ok)throw Error((await response.json().catch(()=>({}))).message||"Cloud request failed ("+response.status+").");return response.status===204?null:response.json(); }
function cloudDraw() { const session=cloudSession();cloud$("#cloudUrl").value=cloudConfig().url||"";cloud$("#cloudKey").value=cloudConfig().key||"";cloud$("#cloudSetup").hidden=!!session;cloud$("#cloudSignedIn").hidden=!session;cloud$("#cloudAccount").textContent=session?"Signed in as "+session.user.email:"";if(!cloudReady()&&!session)cloudSetStatus("Connect your Supabase cloud service to turn on cloud backup."); }
async function cloudRefreshSession() { const session=cloudSession();if(!session?.refresh_token||session.expires_at*1000>Date.now()+60000)return session;const config=cloudConfig(),response=await fetch(config.url.replace(/\/$/,"")+"/auth/v1/token?grant_type=refresh_token",{method:"POST",headers:{apikey:config.key,"Content-Type":"application/json"},body:JSON.stringify({refresh_token:session.refresh_token})});if(!response.ok)throw Error("Your cloud session expired. Please sign in again.");const next=await response.json();localStorage.setItem(CLOUD_SESSION,JSON.stringify(next));return next; }
async function cloudSnapshot() { return {version:1,exportedAt:new Date().toISOString(),transactions:await allTransactions(),monthlyPlans:await recurItems()}; }
async function cloudBackup(silent=false) { if(!cloudReady()||!cloudSession())return;try {const session=await cloudRefreshSession(),data=await cloudSnapshot();await cloudFetch("/rest/v1/my_money_backups?on_conflict=user_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({user_id:session.user.id,data,updated_at:new Date().toISOString()})});cloudSetStatus("Cloud backup saved at "+new Date().toLocaleTimeString()+".");}catch(error){if(!silent)cloudSetStatus(error.message);}}
async function cloudRestore() { try {const session=await cloudRefreshSession(),rows=await cloudFetch("/rest/v1/my_money_backups?user_id=eq."+session.user.id+"&select=data,updated_at");if(!rows.length){cloudSetStatus("No cloud backup found yet.");return}const backup=rows[0].data;if(!backup||!Array.isArray(backup.transactions)||!Array.isArray(backup.monthlyPlans))throw Error("The cloud backup is not valid.");if(!confirm("Restore "+backup.transactions.length+" transactions and "+backup.monthlyPlans.length+" monthly plans from cloud? This replaces data currently on this phone."))return;await clearTransactions();for(const item of backup.transactions)await saveTransaction(item);const planStore=db.transaction(recurStore,"readwrite").objectStore(recurStore);await recurRequest(planStore.clear());for(const item of backup.monthlyPlans)await saveRecur(item);await refresh();await renderRecurring();cloudSetStatus("Cloud backup restored. Last saved "+new Date(rows[0].updated_at).toLocaleString()+".");}catch(error){cloudSetStatus(error.message);}}
async function cloudAuth(signUp=false) { if(!cloudReady()){cloudSetStatus("Save your cloud connection first.");return}const email=cloud$("#cloudEmail").value.trim(),password=cloud$("#cloudPassword").value;if(!email||password.length<8){cloudSetStatus("Enter a valid email and a password with at least 8 characters.");return}try {const config=cloudConfig(),path=signUp?"/auth/v1/signup":"/auth/v1/token?grant_type=password",response=await fetch(config.url.replace(/\/$/,"")+path,{method:"POST",headers:{apikey:config.key,"Content-Type":"application/json"},body:JSON.stringify({email,password})}),data=await response.json();if(!response.ok)throw Error(data.msg||data.message||"Could not sign in.");if(!data.access_token){cloudSetStatus("Account created. Check your email to confirm it, then sign in.");return}localStorage.setItem(CLOUD_SESSION,JSON.stringify(data));cloud$("#cloudPassword").value="";cloudDraw();await cloudBackup();}catch(error){cloudSetStatus(error.message);}}
function queueCloudSync() { clearTimeout(cloudTimer);cloudTimer=setTimeout(()=>cloudBackup(true),1200); }
function cloudSetup() { cloud$("#saveCloudConfig").onclick=()=>{const url=cloud$("#cloudUrl").value.trim().replace(/\/$/,""),key=cloud$("#cloudKey").value.trim();if(!/^https:\/\//.test(url)||!key){cloudSetStatus("Enter a valid HTTPS project URL and publishable/anon key.");return}localStorage.setItem(CLOUD_CONFIG,JSON.stringify({url,key}));cloudSetStatus("Cloud connection saved. Create an account or sign in.");cloudDraw()};cloud$("#cloudSignIn").onclick=()=>cloudAuth();cloud$("#cloudSignUp").onclick=()=>cloudAuth(true);cloud$("#cloudSync").onclick=()=>cloudBackup();cloud$("#cloudRestore").onclick=cloudRestore;cloud$("#cloudSignOut").onclick=()=>{localStorage.removeItem(CLOUD_SESSION);cloudSetStatus("Signed out. Your cloud backup remains safe.");cloudDraw()};cloudDraw() }
const cloudStyle=document.createElement("style");cloudStyle.textContent=".cloud-section{margin-top:25px;padding:17px;border:1px solid #bcdac7;border-radius:16px;background:#f3fbf6}.cloud-section h2{font-size:1.05rem}.cloud-section p{color:#456050;font-size:.8rem;line-height:1.45;margin:5px 0 12px}.cloud-form{display:grid;gap:10px;margin-top:12px}.cloud-form details{background:#fff;padding:10px;border-radius:10px}.cloud-form summary{cursor:pointer;font-size:.82rem;font-weight:750}.cloud-form details p{font-size:.74rem}.cloud-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:11px}.danger-lite{color:#a1251e;border-color:#f1b8b2}";document.head.append(cloudStyle);setTimeout(cloudSetup,700);
