const recurStore="recurring",recur$=s=>document.querySelector(s);
const recurRequest=req=>new Promise((ok,bad)=>{req.onsuccess=()=>ok(req.result);req.onerror=()=>bad(req.error)});
const recurItems=()=>recurRequest(db.transaction(recurStore).objectStore(recurStore).getAll());
const saveRecur=async item=>{const saved=await recurRequest(db.transaction(recurStore,"readwrite").objectStore(recurStore).put(item));if(typeof queueCloudSync==="function")queueCloudSync();return saved};
const deleteRecur=async id=>{const deleted=await recurRequest(db.transaction(recurStore,"readwrite").objectStore(recurStore).delete(id));if(typeof queueCloudSync==="function")queueCloudSync();return deleted};
const recurEscape=value=>String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]));
async function renderRecurring(){const list=recur$("#recurringList"),templates=await recurItems();list.innerHTML=templates.length?templates.map(item=>"<div class='recurring-row'><span><b>"+recurEscape(item.name)+"</b><small>Planned every month on day "+item.day+" · "+(item.type==="income"?"Income":"Expense")+" · "+money(item.amount)+"</small></span><button data-remove='"+item.id+"' aria-label='Remove planned item'>×</button></div>").join(""):"<p class='recurring-empty'>No planned monthly items yet. Add rent, EMI, salary, or a subscription.</p>";list.querySelectorAll("[data-remove]").forEach(button=>button.onclick=async()=>{if(confirm("Remove this planned item?")){await deleteRecur(button.dataset.remove);renderRecurring()}})}
function addPlannedItem(){const dialog=document.createElement("dialog");dialog.innerHTML="<form method='dialog' class='recurring-form'><div class='dialog-heading'><h2>Add planned monthly item</h2><button type='button' class='close-button'>×</button></div><label>Name<input id='rn' placeholder='Example: House rent' required></label><label>Type<select id='rt'><option value='expense'>Monthly expense</option><option value='income'>Monthly income</option></select></label><label>Amount (₹)<input id='ra' type='number' min='0.01' step='0.01' inputmode='decimal' required></label><label>Payment<select id='rm'><option value='cash'>Cash</option><option value='online'>Online</option></select></label><label>Category<input id='rc' value='Bills' required></label><label>Day of month<select id='rd'>"+Array.from({length:28},(_,i)=>"<option value='"+(i+1)+"'>"+(i+1)+"</option>").join("")+"</select></label><label>Note (optional)<input id='rno'></label><button class='save-button'>Save planned item</button></form>";document.body.append(dialog);dialog.querySelector(".close-button").onclick=()=>dialog.close();dialog.querySelector("form").onsubmit=async event=>{event.preventDefault();await saveRecur({id:crypto.randomUUID(),name:dialog.querySelector("#rn").value.trim(),type:dialog.querySelector("#rt").value,amount:Number(dialog.querySelector("#ra").value),mode:dialog.querySelector("#rm").value,category:dialog.querySelector("#rc").value.trim(),day:Number(dialog.querySelector("#rd").value),note:dialog.querySelector("#rno").value.trim()});dialog.close();dialog.remove();renderRecurring()};dialog.showModal()}
async function backupPlans(){const data={app:"My Money planned monthly items",version:1,exportedAt:new Date().toISOString(),items:await recurItems()},url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"})),link=document.createElement("a");link.href=url;link.download="my-money-monthly-plans-backup.json";link.click();URL.revokeObjectURL(url);recur$("#planStatus").textContent="Monthly-items backup downloaded."}
async function restorePlans(input){try{const data=JSON.parse(await input.files[0].text());if(!data||data.version!==1||!Array.isArray(data.items))throw Error();for(const item of data.items)await saveRecur(item);await renderRecurring();recur$("#planStatus").textContent=data.items.length+" planned items restored."}catch{recur$("#planStatus").textContent="That monthly-items backup could not be read."}input.value=""}
function setupRecurring(){const section=document.createElement("section");section.className="recurring-section";section.innerHTML="<div class='section-title'><div><h2>Monthly bills & regular income</h2><p>Planned separately — these do not change your actual monthly balance.</p></div><button class='secondary-button' id='addRecurring'>Add planned item</button></div><div id='recurringList'></div><div class='plan-actions'><button class='secondary-button' id='backupPlans'>Backup monthly items</button><label class='secondary-button'>Restore monthly items<input id='restorePlans' type='file' accept='application/json,.json' hidden></label></div><p id='planStatus' class='status-message'></p>";recur$(".report-section").before(section);recur$("#addRecurring").onclick=addPlannedItem;recur$("#backupPlans").onclick=backupPlans;recur$("#restorePlans").onchange=event=>event.target.files[0]&&restorePlans(event.target);renderRecurring()}
const recurStyle=document.createElement("style");recurStyle.textContent=".recurring-section{margin-top:25px}.recurring-row{display:flex;justify-content:space-between;align-items:center;padding:11px;margin-top:7px;border:1px solid #e2e8e3;border-radius:12px;background:#fff}.recurring-row small{display:block;color:#657169;font-size:.73rem;margin-top:3px}.recurring-row button{border:0;background:#fff0ee;color:#bf3027;border-radius:8px;font-size:1.2rem}.recurring-empty{padding:16px;border:1px dashed #cbd5cb;border-radius:12px;color:#657169;font-size:.82rem}.plan-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}";document.head.append(recurStyle);setTimeout(setupRecurring,600);
