const auth$ = selector => document.querySelector(selector);
const authHash = async value => Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)))).map(item => item.toString(16).padStart(2,"0")).join("");
const authBytes = () => crypto.getRandomValues(new Uint8Array(32));
const authFrom64 = value => Uint8Array.from(atob(value), item => item.charCodeAt(0));
function unlockApp(){auth$("#lockScreen").hidden=true;auth$("#unlockPin").value="";auth$("#unlockMessage").textContent="";window.dispatchEvent(new Event("my-money-unlocked"))}
function lockAtStart(){if(!localStorage.getItem("my-money-pin"))return;auth$("#lockScreen").hidden=false;auth$("#biometricUnlock").hidden=!localStorage.getItem("my-money-biometric")}
async function setPIN(){const pin=prompt("Create a 4 to 12 digit PIN for My Money.");if(!pin||!/^\d{4,12}$/.test(pin)){alert("Please use 4 to 12 digits.");return}if(pin!==prompt("Enter the PIN again.")){alert("PINs did not match.");return}localStorage.setItem("my-money-pin",await authHash(pin));auth$("#securityStatus").textContent="PIN lock is active."}
async function removePIN(){const saved=localStorage.getItem("my-money-pin");if(!saved){auth$("#securityStatus").textContent="No PIN is currently set.";return}const pin=prompt("Enter your current PIN to remove the app lock.");if(!pin)return;if(await authHash(pin)!==saved){alert("Incorrect PIN. The app lock was not changed.");return}localStorage.removeItem("my-money-pin");localStorage.removeItem("my-money-biometric");auth$("#securityStatus").textContent="PIN and phone lock removed."}
async function phoneLock(){if(!window.PublicKeyCredential||!navigator.credentials){auth$("#securityStatus").textContent="Phone lock is not available in this browser.";return}try{const credential=await navigator.credentials.create({publicKey:{challenge:authBytes(),rp:{name:"My Money"},user:{id:authBytes(),name:"local-user",displayName:"My Money user"},pubKeyCredParams:[{type:"public-key",alg:-7}],authenticatorSelection:{authenticatorAttachment:"platform",userVerification:"required"},timeout:60000}});localStorage.setItem("my-money-biometric",btoa(String.fromCharCode(...new Uint8Array(credential.rawId))));auth$("#securityStatus").textContent="Phone lock is ready."}catch{auth$("#securityStatus").textContent="Phone lock setup was cancelled or is not supported."}}
async function usePhoneLock(){try{await navigator.credentials.get({publicKey:{challenge:authBytes(),allowCredentials:[{type:"public-key",id:authFrom64(localStorage.getItem("my-money-biometric"))}],userVerification:"required",timeout:60000}});unlockApp()}catch{auth$("#unlockMessage").textContent="Phone lock did not confirm. Try your PIN."}}
function esc(value){return String(value).replace(/[&<>"']/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]))}
function makePDF(){const items=state.transactions.filter(item=>item.date.startsWith(state.month)).sort((a,b)=>a.date.localeCompare(b.date));const total=totals(items);const rows=items.map(item=>"<tr><td>"+esc(formatDate(item.date))+"</td><td>"+esc(categoryName(item.category))+"</td><td>"+esc(item.mode==="cash"?t("cash"):t("online"))+"</td><td>"+esc(item.note||"—")+"</td><td class='"+item.type+"'>"+(item.type==="income"?"+":"−")+money(item.amount)+"</td></tr>").join("");const win=window.open("","_blank");if(!win){alert("Please allow pop-ups to create the PDF.");return}win.document.write("<!doctype html><title>My Money report</title><style>body{font:14px Arial;padding:25px;color:#17281d}h1{color:#155e3a}.cards{display:flex;gap:12px}.card{border:1px solid #ccdcd0;padding:12px;border-radius:8px}table{border-collapse:collapse;width:100%;margin-top:20px}th,td{border:1px solid #ccdcd0;padding:8px;text-align:left}.income{color:#155e3a}.expense{color:#b42318}@media print{body{padding:0}}</style><h1>My Money</h1><p>Monthly report: "+esc(state.month)+"</p><div class='cards'><div class='card'>Income<br><b>"+money(total.income)+"</b></div><div class='card'>Expenses<br><b>"+money(total.expense)+"</b></div><div class='card'>Balance<br><b>"+money(total.balance)+"</b></div></div><h2>Transactions</h2><table><tr><th>Date</th><th>Category</th><th>Payment</th><th>Note</th><th>Amount</th></tr>"+(rows||"<tr><td colspan='5'>No transactions</td></tr>")+"</table>");win.document.close();setTimeout(()=>win.print(),300)}
auth$("#pdfButton").onclick=makePDF;auth$("#pinButton").onclick=setPIN;auth$("#removePinButton").onclick=removePIN;auth$("#biometricButton").onclick=phoneLock;auth$("#unlockForm").onsubmit=async event=>{event.preventDefault();if(await authHash(auth$("#unlockPin").value)===localStorage.getItem("my-money-pin"))unlockApp();else auth$("#unlockMessage").textContent="Incorrect PIN. Please try again."};auth$("#biometricUnlock").onclick=usePhoneLock;lockAtStart();
function fullPDF(){const items=state.transactions.filter(item=>item.date.startsWith(state.month));const rows=items.map(item=>"<tr><td>"+esc(formatDate(item.date))+"</td><td>"+esc(categoryName(item.category))+"</td><td>"+esc(item.mode)+"</td><td>"+(item.type==="income"?"+":"−")+money(item.amount)+"</td></tr>").join("");const win=window.open("","_blank");if(!win)return;win.document.write("<!doctype html><style>body{font:14px Arial;padding:24px}h1{color:#155e3a}table{border-collapse:collapse;width:100%;margin-top:12px}th,td{border:1px solid #ccdcd0;padding:7px}.calendar-grid{display:grid;grid-template-columns:repeat(7,1fr);gap:4px}.calendar-day{border:1px solid #ccdcd0;padding:5px;min-height:45px}.calendar-day.empty{visibility:hidden}.calendar-weekdays{display:grid;grid-template-columns:repeat(7,1fr);gap:4px;text-align:center;font-weight:bold}.day-total{display:block;font-size:10px}.income{color:#155e3a}.expense{color:#b42318}@media print{body{padding:0}}</style><h1>My Money — "+esc(state.month)+"</h1><h2>Calendar</h2>"+document.querySelector(".calendar-section").innerHTML+"<h2>Transactions</h2><table><tr><th>Date</th><th>Category</th><th>Payment</th><th>Amount</th></tr>"+(rows||"<tr><td colspan='4'>No transactions</td></tr>")+"</table>");win.document.close();setTimeout(()=>win.print(),350)}
auth$("#pdfButton").onclick=fullPDF;
function filteredPDF(){const all=state.transactions.filter(item=>item.date.startsWith(state.month));const items=all.filter(item=>(state.type==="all"||item.type===state.type)&&(state.mode==="all"||item.mode===state.mode)&&(!state.selectedDate||item.date===state.selectedDate));const rows=items.map(item=>"<tr><td>"+esc(formatDate(item.date))+"</td><td>"+esc(categoryName(item.category))+"</td><td>"+esc(item.mode)+"</td><td>"+(item.type==="income"?"+":"−")+money(item.amount)+"</td></tr>").join("");const label=(state.selectedDate?formatDate(state.selectedDate)+" · ":"")+("Type: "+state.type+" · Payment: "+state.mode);const win=window.open("","_blank");if(!win)return;win.document.write("<!doctype html><style>body{font:14px Arial;padding:24px}h1{color:#155e3a}table{border-collapse:collapse;width:100%;margin-top:12px}th,td{border:1px solid #ccdcd0;padding:7px;text-align:left}.calendar-grid{display:grid;grid-template-columns:repeat(7,1fr);gap:4px}.calendar-day{border:1px solid #ccdcd0;padding:5px;min-height:45px}.calendar-day.empty{visibility:hidden}.calendar-weekdays{display:grid;grid-template-columns:repeat(7,1fr);gap:4px;text-align:center;font-weight:bold}.day-total{display:block;font-size:10px}@media print{body{padding:0}}</style><h1>My Money — "+esc(state.month)+"</h1><p>Applied filters: "+esc(label)+"</p><h2>Monthly calendar</h2>"+document.querySelector(".calendar-section").innerHTML+"<h2>Filtered transactions</h2><table><tr><th>Date</th><th>Category</th><th>Payment</th><th>Amount</th></tr>"+(rows||"<tr><td colspan='4'>No matching transactions</td></tr>")+"</table>");win.document.close();setTimeout(()=>win.print(),350)}
auth$("#pdfButton").onclick=filteredPDF;
